# fly.toml app configuration file generated for aditya-notes-api on 2025-09-13T16:43:05-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aditya-notes-api"
primary_region = 'sjc'
kill_signal = 'SIGINT'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
